language: python
python: 3.6
install:
  - pip install --upgrade pip
  - pip install .
  - pip install cython
  - pip install git+https://bitbucket.org/lbl-cascade/fastkde.git#egg=fastkde
script: pytest
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true